export const IS_AUTHENTICATED = 'IS_AUTHENTICATED' 
export const IS_ALREADY_AUTHENTICATED = 'IS_ALREADY_AUTHENTICATED' 
export const INVALID_USER ='INVALID_USER' 
export const REMOVE_TOKEN = 'REMOVE_TOKEN'

